import Foundation
import FrontEnd
import Logging

/// A build-system-agnostic description of a Hylo module graph.
///
/// A build system (CMake, Bazel, a future SPM-like tool) emits this as a
/// `hylo-project.json` file so the language server can group a workspace's files
/// into modules and order their imports without knowing anything about the build
/// system. It is the static-artifact analogue of rust-analyzer's
/// `rust-project.json`: the unit is the *module*, not the source file, because
/// Hylo type-checks a whole module at once.
///
/// The format is specified field-by-field in `docs/hylo-project.schema.json`.
public struct HyloProjectManifest: Codable, Sendable {

  /// One Hylo module: a set of source files compiled together, plus the modules
  /// it imports.
  ///
  /// A module's sources are the union of `sources` (explicit files) and the
  /// recursive `.hylo` scan of `sourceRoot` (one directory). At least one of the
  /// two is expected; a module named `Module.standardLibraryName` (`"Hylo"`) is the
  /// standard library and must not depend on itself.
  public struct ModuleDescription: Codable, Sendable {

    /// The module's name, as written in `import` statements.
    public var name: String

    /// The build target that contributed these sources, if any.
    ///
    /// Only for diagnostics/traceability. Because two targets can define
    /// modules of the same `name` (e.g. two executables' `Main`), `name` alone
    /// is not a workspace-unique key; `(originTarget, name)` is.
    public var originTarget: String?

    /// The published `.hylomodule` archive, if the build produced one.
    ///
    /// When present and fresh, a server may load the interface from here instead
    /// of recompiling the module from sources.
    public var archive: String?

    /// The names of the modules this one imports (direct edges only).
    public var imports: [String]

    /// The absolute paths of this module's explicitly listed `.hylo` sources.
    public var sources: [String]

    /// A single directory whose `.hylo` files (searched recursively) all belong to
    /// this module. Relative paths are resolved against the manifest's directory.
    public var sourceRoot: String?

    public init(
      name: String, originTarget: String? = nil, archive: String? = nil,
      imports: [String] = [], sources: [String] = [], sourceRoot: String? = nil
    ) {
      self.name = name
      self.originTarget = originTarget
      self.archive = archive
      self.imports = imports
      self.sources = sources
      self.sourceRoot = sourceRoot
    }

    private enum CodingKeys: String, CodingKey {
      case name, originTarget, archive, imports, sources, sourceRoot
    }

    /// Decodes a module, defaulting the optional collection fields to empty so that
    /// a terse `{ "name": "Hylo", "sourceRoot": "Sources" }` is valid.
    public init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      name = try c.decode(String.self, forKey: .name)
      originTarget = try c.decodeIfPresent(String.self, forKey: .originTarget)
      archive = try c.decodeIfPresent(String.self, forKey: .archive)
      imports = try c.decodeIfPresent([String].self, forKey: .imports) ?? []
      sources = try c.decodeIfPresent([String].self, forKey: .sources) ?? []
      sourceRoot = try c.decodeIfPresent(String.self, forKey: .sourceRoot)
    }
  }

  /// The manifest schema version.
  public var schemaVersion: Int

  /// The standard library's root source directory, if the build system knows it.
  ///
  /// Advisory: only a fallback for locating the stdlib when the graph does not
  /// itself contain a module named `"Hylo"`.
  public var stdlibRoot: String?

  /// The compilation target triple, if specified.
  public var target: String?

  /// The modules in the workspace.
  public var modules: [ModuleDescription]

  public init(
    schemaVersion: Int, stdlibRoot: String? = nil, target: String? = nil,
    modules: [ModuleDescription]
  ) {
    self.schemaVersion = schemaVersion
    self.stdlibRoot = stdlibRoot
    self.target = target
    self.modules = modules
  }
}

/// A workspace-unique identity for a module: two targets may define modules of the
/// same `name`, so the pair disambiguates them.
public struct ModuleKey: Hashable, Sendable {

  /// The target of which this module is part of, if applicable.
  ///
  /// May be absent if the manifest is not generated by a build system.
  public let originTarget: String?
  
  /// The name of the module.
  public let name: String

  /// Creates an instance from its parts.
  public init(originTarget: String?, name: String) {
    self.originTarget = originTarget
    self.name = name
  }
}

/// Discovers and interprets `hylo-project.json` manifests, and turns them into an
/// ordered, on-disk-resolved plan for the whole workspace.
public enum ProjectModel {

  /// The manifest file name a build system emits at a workspace root.
  public static let manifestFileName = "hylo-project.json"

  /// One module to compile, resolved to on-disk source URLs.
  public struct ModulePlan: Sendable, Equatable {

    /// The module's name.
    public let name: String

    /// The build target that contributed the module, if any.
    public let originTarget: String?

    /// The names of the modules it imports.
    public let imports: [String]

    /// The module's source files, with `sourceRoot` already expanded.
    public let sources: [URL]

    /// The symlink-resolved path of each element of `sources`, resolved once at plan
    /// construction so no request-path code touches the filesystem for identity.
    public let resolvedSourcePaths: [String]

    /// The symlink-resolved directory recursively scanned for this module's sources when the
    /// manifest declares a `sourceRoot`. A file created or deleted under it changes the
    /// module's file set without any manifest edit, so plan invalidation must watch it.
    public let sourceRootDirectory: String?

    /// The manifest file that declared the module, if any (synthesized plans have none).
    public let manifest: URL?

    /// The module's workspace-unique identity.
    public var key: ModuleKey { ModuleKey(originTarget: originTarget, name: name) }

    public init(
      name: String, originTarget: String?, imports: [String], sources: [URL],
      sourceRootDirectory: String? = nil, manifest: URL? = nil
    ) {
      self.name = name
      self.originTarget = originTarget
      self.imports = imports
      self.sources = sources
      self.resolvedSourcePaths = sources.map { $0.resolvingSymlinksInPath().path }
      self.sourceRootDirectory = sourceRootDirectory
      self.manifest = manifest
    }
  }

  /// A topologically ordered plan for a whole workspace, plus the reverse index
  /// mapping each source file (by symlink-resolved path) to its owning module.
  ///
  /// `Equatable` so cache invalidation can tell a manifest *rewrite* from a manifest *change*:
  /// two plans are equal iff they resolve the same modules with the same imports and sources.
  public struct WorkspacePlan: Sendable, Equatable {

    /// The modules to compile, dependencies before dependents and `"Hylo"` first.
    public let modules: [ModulePlan]

    /// Maps a symlink-resolved source path to the module that owns it.
    public let fileToModule: [String: ModuleKey]

    /// The key of the first-declared module of each name — the resolution import edges use.
    private let keyByName: [String: ModuleKey]

    /// down(M) per module: the module, its transitive imports, and the standard library (an
    /// implicit dependency of every module). Computed once at construction — `modules` is
    /// topologically ordered, so each module's closure is its imports' closures plus itself.
    private let downClosures: [ModuleKey: Set<ModuleKey>]

    /// Whether any module's import fails to resolve or participates in a cycle — a graph
    /// program construction must refuse.
    public private(set) var hasUnresolvableImports = false

    public init(modules: [ModulePlan], fileToModule: [String: ModuleKey]) {
      self.modules = modules
      self.fileToModule = fileToModule

      var byName: [String: ModuleKey] = [:]
      for m in modules where byName[m.name] == nil { byName[m.name] = m.key }
      self.keyByName = byName

      // The stdlib is an implicit dependency of every module (and of itself, harmlessly).
      let stdlibKeys = Set(modules.filter { isStandardLibrary($0.name) }.map(\.key))
      var closures: [ModuleKey: Set<ModuleKey>] = [:]
      var invalid = false
      for m in modules {
        var down = stdlibKeys
        down.insert(m.key)
        for importedName in m.imports {
          // Dependencies precede dependents in `modules`, so their closures are already
          // computed. A name that resolves to nothing, or to a module whose closure is not yet
          // computed (a cycle participant), makes the graph unbuildable.
          if let dependency = byName[importedName], let dependencyDown = closures[dependency] {
            down.formUnion(dependencyDown)
          } else {
            invalid = true
          }
        }
        closures[m.key] = down
      }
      self.downClosures = closures
      self.hasUnresolvableImports = invalid
    }

    /// Only the resolved structure identifies a plan; the derived tables follow from it.
    public static func == (l: WorkspacePlan, r: WorkspacePlan) -> Bool {
      l.modules == r.modules && l.fileToModule == r.fileToModule
    }

    /// The key of the first-declared module named `name`, mirroring how import edges are
    /// resolved when the plan is constructed.
    public func key(named name: String) -> ModuleKey? {
      keyByName[name]
    }

    /// The keys of down(M) for the module identified by `key`: the module plus its transitive
    /// imports, and the standard library.
    public func downClosureKeys(of key: ModuleKey) -> Set<ModuleKey> {
      downClosures[key] ?? [key]
    }

    /// The keys of closure(M) for the module identified by `key`: the union of down(R) for every
    /// `R` whose down-closure contains the module (its transitive dependents, and itself). This
    /// is the smallest import-closed set containing the module and all its dependents — the
    /// program needed to find every reference to a symbol the module declares.
    public func closureKeys(of key: ModuleKey) -> Set<ModuleKey> {
      var result = downClosureKeys(of: key)
      for (_, down) in downClosures where down.contains(key) {
        result.formUnion(down)
      }
      return result
    }

    /// The plans of `keys`, in this plan's order (dependencies before dependents, stdlib first),
    /// so the result can be handed to program construction directly.
    public func modules(in keys: Set<ModuleKey>) -> [ModulePlan] {
      modules.filter { keys.contains($0.key) }
    }
  }

  /// Conventional out-of-source build directory names to probe for a manifest,
  /// since a build system typically writes it into the build tree rather than
  /// beside the sources. `*build*` variants (e.g. `cmake-build-debug`) are matched
  /// separately, so they need not be listed here.
  static let buildDirectoryNames = ["out", ".hylo"]

  /// True iff `name` looks like a conventional build directory.
  static func looksLikeBuildDirectory(_ name: String) -> Bool {
    let lower = name.lowercased()
    return lower.contains("build") || buildDirectoryNames.contains(lower)
  }

  /// Returns true iff `name` denotes the standard-library module. (`Module.Name` is
  /// `String`, so this is a plain name comparison against `Module.standardLibraryName`.)
  static func isStandardLibrary(_ name: String) -> Bool {
    name == Module.standardLibraryName
  }

  // MARK: - Discovery

  /// Discovers every readable `hylo-project.json` relevant to `file` and the
  /// workspace, paired with the directory each was found in (used to resolve a
  /// module's relative `sourceRoot`).
  ///
  /// Candidates are collected, in priority order, from `explicitPaths` (e.g. a
  /// client-configured build directory), then every ancestor of `file` AND that
  /// ancestor's conventional build subdirectories, then each `workspaceFolder` root
  /// and its build subdirectories — so an out-of-source build-tree manifest is
  /// found. Unlike a per-file resolve, *all* readable manifests are returned so the
  /// whole workspace graph can be assembled; duplicates (by path) and unparseable
  /// files are skipped.
  public static func discoverManifests(
    for file: URL?,
    workspaceFolders: [URL] = [],
    explicitPaths: [URL] = [],
    logger: Logger? = nil
  ) -> [(manifest: HyloProjectManifest, directory: URL)] {
    var candidates: [URL] = explicitPaths.map {
      $0.hasDirectoryPath || $0.pathExtension.isEmpty
        ? $0.appendingPathComponent(manifestFileName) : $0
    }

    if let file {
      var directory = file.deletingLastPathComponent()
      while true {
        candidates.append(directory.appendingPathComponent(manifestFileName))
        candidates.append(contentsOf: buildSubdirectoryManifests(of: directory))
        let parent = directory.deletingLastPathComponent()
        if parent.path == directory.path { break }
        directory = parent
      }
    }

    for folder in workspaceFolders {
      candidates.append(folder.appendingPathComponent(manifestFileName))
      candidates.append(contentsOf: buildSubdirectoryManifests(of: folder))
    }

    var searched: Set<String> = []
    var result: [(HyloProjectManifest, URL)] = []
    for candidate in candidates {
      guard searched.insert(candidate.path).inserted else { continue }
      guard FileManager.default.fileExists(atPath: candidate.path) else { continue }
      do {
        let manifest = try JSONDecoder().decode(
          HyloProjectManifest.self, from: try Data(contentsOf: candidate))
        result.append((manifest, candidate.deletingLastPathComponent()))
      } catch {
        logger?.error("Project model: skipping unreadable manifest \(candidate.path): \(error)")
      }
    }
    return result
  }

  /// Manifest paths inside `directory`'s conventional build subdirectories.
  static func buildSubdirectoryManifests(of directory: URL) -> [URL] {
    let subdirectories =
      (try? FileManager.default.contentsOfDirectory(
        at: directory, includingPropertiesForKeys: [.isDirectoryKey])) ?? []
    return
      subdirectories
      .filter {
        looksLikeBuildDirectory($0.lastPathComponent)
          && (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true
      }
      .map { $0.appendingPathComponent(manifestFileName) }
  }

  // MARK: - Source resolution

  /// The on-disk source URLs of `module`: its explicit `sources` unioned with the
  /// recursive `.hylo` scan of `sourceRoot` (resolved against `manifestDirectory`
  /// when relative).
  public static func resolvedSources(
    of module: HyloProjectManifest.ModuleDescription, manifestDirectory: URL
  ) -> (sources: [URL], sourceRootDirectory: String?) {
    var urls = module.sources.map { URL(fileURLWithPath: $0) }
    var rootDirectory: String?
    if let root = module.sourceRoot {
      let rootURL = URL(fileURLWithPath: root, relativeTo: manifestDirectory)
      rootDirectory = rootURL.resolvingSymlinksInPath().path
      let found =
        (try? FileManager.default.files(under: rootURL, where: { $0.pathExtension == "hylo" }))
        ?? []
      urls.append(contentsOf: found)
    }
    return (urls, rootDirectory)
  }

  // MARK: - Whole-workspace plan

  /// Assembles a single topologically ordered plan for the whole workspace from all
  /// discovered `manifests`.
  ///
  /// Modules are keyed by `(originTarget, name)`; the first description of a key
  /// wins if two manifests define it. The `"Hylo"` module (the standard library) is
  /// forced first — nothing lists it in `imports`, but every module implicitly
  /// depends on it. Imports are resolved by name; the closure is walked with a
  /// cycle-safe visited set. `fileToModule` maps every module's sources
  /// (symlink-resolved) to its key.
  public static func workspacePlan(
    from manifests: [(manifest: HyloProjectManifest, directory: URL)]
  ) -> WorkspacePlan {
    var descriptionByKey: [ModuleKey: (HyloProjectManifest.ModuleDescription, URL)] = [:]
    var declarationOrder: [ModuleKey] = []
    for (manifest, directory) in manifests {
      for module in manifest.modules {
        let key = ModuleKey(originTarget: module.originTarget, name: module.name)
        if descriptionByKey[key] == nil {
          descriptionByKey[key] = (module, directory)
          declarationOrder.append(key)
        }
      }
    }

    func plan(for key: ModuleKey) -> ModulePlan {
      let (module, directory) = descriptionByKey[key]!
      let resolved = resolvedSources(of: module, manifestDirectory: directory)
      return ModulePlan(
        name: module.name, originTarget: module.originTarget, imports: module.imports,
        sources: resolved.sources, sourceRootDirectory: resolved.sourceRootDirectory,
        manifest: directory.appendingPathComponent(manifestFileName))
    }

    // Import edges are by name; resolve to the first declared key of that name.
    func dependencyKey(named name: String) -> ModuleKey? {
      declarationOrder.first { $0.name == name }
    }

    var visited: Set<ModuleKey> = []
    var ordered: [ModulePlan] = []
    func visit(_ key: ModuleKey) {
      guard visited.insert(key).inserted else { return }
      let p = plan(for: key)
      for importedName in p.imports {
        if let dependency = dependencyKey(named: importedName) { visit(dependency) }
      }
      ordered.append(p)
    }

    // `"Hylo"` first (it has no imports, so it lands at the front), then the rest.
    for key in declarationOrder where isStandardLibrary(key.name) { visit(key) }
    for key in declarationOrder where !isStandardLibrary(key.name) { visit(key) }

    var fileToModule: [String: ModuleKey] = [:]
    for p in ordered {
      for path in p.resolvedSourcePaths {
        fileToModule[path] = p.key
      }
    }
    return WorkspacePlan(modules: ordered, fileToModule: fileToModule)
  }

}
